title: ""
author: "Hao-Wei Liang"
description: "National Taiwan University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon} 
  - {file: "index.html", title: "Home"}
  - {file: "Honors.html", title: "Honors"}
  - {file: "blog.html", title: "Blog"}
  - {url: "/CV_Hao_Wei_8_26.pdf", title: "CV"}
  - {file: "/test/index.html", title: "Test"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:b07502022@ntu.edu.tw"}
  - {title: Github, icon: github, url: "https://github.com/Howard-Liang"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/%E7%9A%93%E7%91%8B-%E6%A2%81-97063a225/?locale=en_US"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

